### ISSUE TITLE
Game freezes when using Smugglers after Black Market card was purchased

### ISSUE THREAD

**Issue by michalbe** [jcbantuelle/dominion-meteor#19]
Debug log:

```
Exception in callback of async function: TypeError: Cannot read property 'top_card' of undefined
    at app/cards/seaside/smugglers.js:19:35
    at arrayFilter (/srv/http/…/bundle/programs/server/npm/node_modules/meteor/stevezhu_lodash/node_modules/lodash/lodash.js:588:11)
    at Function.filter (/srv/http/…/bundle/programs/server/npm/node_modules/meteor/stevezhu_lodash/node_modules/lodash/lodash.js:8837:14)
    at Smugglers.play (app/cards/seaside/smugglers.js:15:28)
    at CardPlayer.play_card (app/game/server/services/card_player.js:80:26)
    at CardPlayer.play (app/game/server/services/card_player.js:28:33)
    at app/game/server/game.js:33:23
```

**Comment by jcbantuelle** [comment]
Good catch! Thank you for the feedback, I've pushed a fix.
